package com.none.svmwrapper;

import libsvm.svm_model;

/**
 * This class contains logic to use the svm_model generated by Train
 * to predict the class label for unclassified data.<br><br>
 * 
 * Code is a simplified version of libsvm's svm_predict.java<br><br>
 * 
 * @author jharper
 *
 */
public class Predict
{
	private svm_model model;
	
	public Predict(svm_model model)
	{
		this.model = model;
	}
}
